### PR TITLE
FromScratch with Sidebar

### PR DESCRIPTION
**Pull request by Brachacz**

### CODE REVIEW

**Comment by Kilian** [comment]
I'll look at this over the weekend, but there are a number of changes I would already like to make:

- no roboto or ionicons ;)
- keep a single react root for easier state management
- use electon IPC instead of a homebrew pub/sub system

**Comment by Brachacz** [comment]
- Roboto

Why not? Saves a ton of space when compared to Fira (which is monospace). Using Fira in sidebar would be compromising readability for font consistency. My point of view is that FromScratch component is 'editor' or 'content' part while Sidebar is strictly UI - using better suited font for UI is justified.

- Ionicons

If you don't like them, I could make (and so I did in the early phases) make some kind of ::before indicators for project/scratch items but accomodating rename/remove/add controls would be really problematic without icons.

- Single root and IPC

Sure can do, FromScratch is my first dev contact with both React and Electron so I thought 'if it works then why not' ;D. Will refactor next week.

All in all, when it comes to Roboto and Ionicons, please check out the final effect before deciding. In my opinion it looks really good and integrate nicely into FromScratch aesthethic. If you decide you really don't like them, I will keep and maintain two branches, one to merge here, other as private ;)

**Comment by Kilian** [comment]
I'll reserve judgement!

**Comment by Kilian** [comment]
*Just a word of warning, I am opinionated and picky when it comes to what I want to add to Fromscratch proper, so don't be alarmed if I come with a ton of requests. Here's a wall of text ;)*

First off, the way the sidebar currently works is pretty impressive, especially for a first-time React user. Great job! For many apps this would get my instant approval. 

However, it's too complex for FromScratch from a product design perspective (as well as a code perspective). Fromscratch should be nothing more and nothing less than a square to offload your brain in. Whether that's a todo list, some quick notes or a draft version of something doesn't matter. Fromscratch gets out of the way: no UI means nothing to worry about when typing. No need to do markup or any sort of management. This is very important to me and it's (I think) why it's proven to be so popular. 

Adding a sidebar adds a form of management and a form of UI, so it should only be done in a way that is totally unobtrusive: like how search stays fully out of your way until you press ctrl + f, or how the scrollbar only appears when there's something to scroll. 

**Initially, I wrote down a long list of feedback** but then I started thinking on how I would implement the sidebar in a way that I feel works with FromScratch. Here is the list still because I think it's valuable for you, but below that is my description of the type of sidebar that I would add to FromScratch without necessarily looking at what you've already built.

Here's a couple of big things that I would change in this sidebar:
- The differentiation between projects and scratches is a level too much. I get where you're coming from, but FromScratch should not be a note organising tool and a sidebar with different notes is already a relatively large mental barrier for an app to quickly store your thoughts in. 
- The default workspace should be part of the list. Maybe part of the list but not deletable.
- Should work entirely with the keyboard as well.
- It should be simple to switch to a previous or next scratch, two click or one keyboard shortcut at most. You're pretty much there if we remove the projects, but it's a good rule of thumb to check features against.

Minor things I want to change:
- Clicking outside of the sidebar should close it
- Hover animations should be much more subtle (no moving text)
- Center-aligned text is probably not the easiest to read
- There is too much explanatory text: While it might seem like you need it initially, the rest of FromScratch depends far more on learnability instead. I'd like us to have the least amount of UI required for this.
- The scrollbar behaves differently from the regular scrollbar (that one widens and gains contrast slightly when you hover over it)
- With the sidebar closed, the text area is no longer properly horizontally centered
- I really don't like Roboto or Ionicons here, sorry. Keeping this Fira Code makes it work much better for me, and for the icons I like react-bytesize-icons as they can be a little more legible when smaller.
- The gradient border is interesting, but I would prefer the sidebar in it's entirety to have a slight color difference similar to the search bar.
- I'd like for people that don't use the sidebar to never have to see it (Just like the other additions I have made since v1), which means that the current chevron/arrow is too prominent (and should probably be hidden until the user uses a shortcut)

There's also some other things to think about:

- Scratches are laid out alphabetically now and people will want to change that.
- Adding a Scratch created a new row: Why not show the input field inside that row? Enter applies and creates, esc or clicking outside cancels. This saves you a dialog.
- Pull request #56 adds in support for moving the default scratch. How should these interact? 
- I think we should save all text in a single text file (and use a certain keystring as a separator?) 


**How I would like the sidebar to work:**

For me, ideally, it would be a simple list where the "title" of an item is determined by the first line (or first word?) of the scratch. The last item in the list is always a "new" empty scratch. As soon as you type into that, it counts as a new scratch and gets it's own item in the list. As soon as you fully empty a scratch and move away from it, I think it should be automatically removed from the list. The sidebar should not be visible in normal FromScratch usage, but should be made visible with a shortcut. You should be able to use the up/down arrow keys and enter to move to a different scratch. Moving to a different scratch should close the sidebar. It should be possible to reorder these scratches using drag and drop, or ctrl+up/ctrl-down like you can move lines. 

Technically, I think I would want to keep all scratches in a single text file. Scratches would get separated using a certain long keystring, parsed and separated on read and joined on write. This makes it super easy to build on top of the existing code. This would also make it very easy to integrate with #56 which I hope we can add soon.

**I hope I haven't discouraged you too much, I do see the value in a sidebar to quickly switch around contexts, but I want to do so in the least intrusive way possible.**

**Comment by Brachacz** [comment]
Thanks for thorough feedback :)

I don't think that's discouraging, on the contrary, it's really nice that you took the time to look it through, as well as that you have clear vision for the project. I'm also happy that there's a real project that I can contribute to to learn React. Implementing all of this will take some time though as this is a side project unrelated to my job. 

I felt the need for sidebar (and maybe tabs in the future) because I use FromScratch for taking notes that I want to not only be easy to manipulate but also accessible. I often need to 'consult' myself with something I braindumped some time ago and then quickly return to what I was doing in the first place. I'd use Boostnote which already has sidebar/tabs/themes but Boostnote only allows me to write Markdown and switching between 'source' and compiled Markdown successfully disrupts train of thought. On the other side, FromScratch allows me to focus on problem solving not because of absence of UI but rather by enabling me to freely manipulate the content along with FiraCode ligatures - at this point this feeling of freedom in shaping my thoughts it's irreplaceable for me.

Now, a fully fledged note oragnizing tool is not what you intended FromScratch to be so I will make the changes you suggested in a following fashion - **first, I will implement changes that are in line with both yours and mine use cases,** then branch out and adjust for desired simplicity for the pull request to be accepted into FromScratch. **At the same time I will keep developing my fork that satisfies my needs.**

Changes that are in line with both yours and mine spec:

- single react root
- signalEmitter -> IPC
- default workspace -> part of the list,
- sidebar keyboard support (+ switch to last scratch),
- hover animations should be much more subtle (no moving text),
- center-aligned text is probably not the easiest to read,
- too much explanatory text,
- scrollbar behaves differently from the regular scrollbar
- with the sidebar closed, the text area is no longer properly horizontally centered
- only show sidebar / chevron on keyboard shortcut
- manual rearrangement of scratches (keyboard shortcut)
- input as new row

Changes just for master FromScratch:

- clicking outside of the sidebar should close it,
- no roboto / ionicons
- sidebar background
- support for moving default scratch
- single parsed text file storage
- automatic naming based on first word of the scratch
- last scratch -> new scratch, persist on content, 
- remove empty scratch that lost focus
- moving to a different scratch closes the sidebar

I've got a comment for every of these matters about why it has been done this way and not another but this post would be veeery long if I write it here so I will comment each matter as I progress with implementation.

**Is all of the above acceptable for you?**

**Comment by Kilian** [comment]
Glad to hear! I have some reservations on the two-step process (I fear it might lead to unneeded complexity in the code for want of supporting other things) but it's a good plan. Would you consider switching it around, where you build the FromScratch-sidebar first, then built on top of that your additional wishes?

**Comment by Brachacz** [comment]
Code will actually be more concise this way because I won't have to support multiple contradicting functionalities in one codebase. I want to avoid mess by separating branches when they no longer align, neither will contain any unnecessary code then.

I want to do it in the order above so I can also benefit from certain changes in my personal branch :D
When I split branches, FromScratch-sidebar will be the first I will work on and effectively its development will be consistently progressive. I don't want to implement changes that don't align with my use case first because I want to keep project/scratch structure and some other things and I would have to implement it back which is a wasted time.

Since not completed pull request won't be merged anyway, I don't think the order of implementation itself makes any difference ;)

**Comment by Brachacz** [comment]
Just wanted to notify that I remember about this and I have not been discouraged as you previously feared, just had a really busy period (college graduation, huge project at work etc). :)

On the other note, would it be ok for you if I used rxjs and Redux to manage synchronised component state?

**Comment by Kilian** [comment]
@Brachacz no rush ;) rxjs and redux are nice, but I don't think they're needed. I prefer props + callbacks for this!

**Comment by Kilian** [comment]
closing, continues in #58

**Pull request closed without merging**
